[options]
admin_passwd = $pbkdf2-sha512$600000$6V2LUSoFQOj9f6/V.n9P6Q$L7bGPEFoc6biSZTCPPh7PlNiS1oA53cg.VTWFIHTFxSaeTnm47bNrzd7FN3SRqhgC2m5TR6mdt83j3zT2Gny0g
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = C:\Users\aniru\Documents\Odoo19DevEnv\odoo\addons,C:\Users\aniru\Documents\Odoo19DevEnv\custom_addons

